name: samurai-0.27
channels:
  - conda-forge
dependencies:
  - cmake
  - cli11
  - h5py
  - cxx-compiler
  - samurai>=0.27
  - matplotlib
  - libboost-mpi
  - libboost-devel
  - libboost-headers
  - 'hdf5=*=mpi*'
